apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: unified-nodeclass
spec:
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: prod-cluster
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: prod-cluster
  amiFamily: AL2023
  role: karpenter-role
  tags:
    Name: unified-karpenter
    karpenter.sh/discovery: prod-cluster
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: unified-nodepool
spec:
  template:
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: unified-nodeclass
      requirements:
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64", "arm64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot", "on-demand"]
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["c", "m", "r"]
        - key: "karpenter.k8s.aws/instance-cpu"
          operator: In
          values: ["4", "8", "16", "32"]
        - key: "karpenter.k8s.aws/instance-hypervisor"
          operator: In
          values: ["nitro"]
        - key: "karpenter.k8s.aws/instance-generation"
          operator: Gt
          values: ["2"]
  limits:
    cpu: 3000
  disruption:
    consolidationPolicy: WhenEmpty